name: todo_p1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  uuid: ^4.3.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  hive_generator: 

flutter:
  uses-material-design: true
